### PR TITLE
Update for compatibility with modern libctru.

### PR DESCRIPTION
**Pull request by sirocyl**

### CODE REVIEW

**Comment by smealum** [comment]
have you tested this?

**Comment by sirocyl** [comment]
No promises if it'll work on 11.x, but it builds successfully on Ubuntu with everything up to date in the dkp repos. I don't have my 3DS's with me at the moment, so I can't vouch for it running.

**Comment by smealum** [comment]
totally forgot about this PR, looks like neobrain just submitted the exact same thing and it's been merged. so, sorry about this, I do appreciate you taking time to fix it and again sorry for not merging it last year.

**Comment by sirocyl** [comment]
It's okay. Maybe if I was a known and established developer it would've been merged. Thanks for the acknowledgement though!

**Pull request closed without merging**
